migrating to networkd
dd-ix/nix-config pull request #2
Opened 2023-07-08 21:21 UTC by revol-xut

## Why this change

- Scripted networking sucks
- Machines run with systemd anyway, so I would go the full way
- networkd is very declarative and verbose

2023-07-09 18:43 UTC, liske requested changes

2023-07-09 18:43 UTC, liske commented on hosts/mno001/network.nix
> +      "9.9.9.9" # QUAD 9
Those resolvers are used in parallel which might not your intention. The IBH ns should be moved to resolved's [DNS](https://www.freedesktop.org/software/systemd/man/resolved.conf.html#DNS=) option and quad9 kept as [FallbackDNS](https://www.freedesktop.org/software/systemd/man/resolved.conf.html#FallbackDNS=).

2023-07-12 00:44 UTC, revol-xut commented
I/We would merge & deploy this next time we are in the data center.

2023-07-15 21:20 UTC, liske approved these changes
Approving, although I have no glue about nix nor networkd :shrug:

2024-01-05 21:15 UTC, merged